# Generated by Django 5.0.1 on 2024-01-25 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=36)),
                ("days_of_test", models.PositiveIntegerField(max_length=2)),
                ("days_of_use_as_premiun", models.PositiveIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="TestAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_for_test", models.DateField(auto_now_add=True)),
                ("has_finish", models.BooleanField(default=False)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiunAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_for_use", models.DateField(auto_now_add=True)),
                ("has_finish", models.BooleanField(default=False)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.userprofile",
                    ),
                ),
            ],
        ),
    ]
