# Generated by Django 5.0.1 on 2024-01-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_days_of_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testaccount',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='day_for_premiun_use',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='days_for_test',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premiun_days_has_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tests_days_has_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='days_of_test',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='days_of_use_as_premiun',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.DeleteModel(
            name='PremiunAccount',
        ),
        migrations.DeleteModel(
            name='TestAccount',
        ),
    ]
