# Generated by Django 5.0.1 on 2024-01-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0003_remove_testaccount_user_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="day_for_premiun_use",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="days_for_test",
            field=models.DateField(auto_now_add=True),
        ),
    ]
