# Generated by Django 5.0.1 on 2024-01-26 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0004_alter_userprofile_day_for_premiun_use_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="premiun_days_has_finish",
            new_name="premiun_days_selected",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="tests_days_has_finish",
            new_name="tests_days_selected",
        ),
    ]
