# Generated by Django 5.0.1 on 2024-01-26 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "userprofile",
            "0006_rename_day_for_premiun_use_userprofile_days_for_premiun_use_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="days_for_premiun_use",
            new_name="start_date_for_premiun_use",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="days_for_test",
            new_name="start_date_for_test",
        ),
    ]
